name: Release MicroAlign (from last Build artifacts)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create/release (e.g. v0.1.7)"
        required: true
      branch:
        description: "Branch to pull artifacts from"
        required: false
        default: "main"

permissions:
  contents: write
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for tagging)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download artifacts from the latest successful Build MicroAlign on branch
      - name: Download artifacts from last successful Build MicroAlign
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ github.token }}
          workflow: build.yml
          workflow_conclusion: success
          branch: ${{ inputs.branch }}
          name: ""              # download all artifacts
          path: dist
          if_no_artifact_found: fail

      - name: List downloaded
        run: ls -lah dist || true

      - name: Create tag if missing
        run: |
          set -e
          TAG="${{ inputs.tag }}"
          git fetch --tags
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
          else
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: MicroAlign ${{ inputs.tag }}
          generate_release_notes: true
          files: |
            dist/MicroAlign-macOS.zip
            dist/MicroAlign-Windows.zip
            dist/MicroAlign-Linux.tar.gz
