name: Release MicroAlign (rebuild on tag)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional: tag to build & release (if not using tag push)"
        required: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build/package/upload (same as Build workflow)
        uses: ./.github/actions/build_microalign
        with:
          app-name: MicroAlign
          bundle-id: com.yourco.microalign
          icon-base: align_app/assets/AppIcons/Assets.xcassets/AppIcon.appiconset/1024.png

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: MicroAlign-*
          merge-multiple: true
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || inputs.tag }}
          name: MicroAlign ${{ github.ref_type == 'tag' && github.ref_name || inputs.tag }}
          generate_release_notes: true
          files: |
            dist/MicroAlign-macOS.zip
            dist/MicroAlign-Windows.zip
            dist/MicroAlign-Linux.tar.gz
