name: Publish from last Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create/release (e.g. v0.1.5)"
        required: true
      branch:
        description: "Branch to search for the last successful Build run"
        required: false
        default: "main"
      run_id:
        description: "Optional: specific Build workflow run-id to use"
        required: false
      title:
        description: "Release title (defaults to tag)"
        required: false
      notes:
        description: "Release notes (optional)"
        required: false

permissions:
  contents: write   # create tags + releases
  actions: read     # download artifacts from another run

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for tagging)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve the build run to use
        id: resolve
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "${{ inputs.run_id }}" ]; then
            echo "Using provided run_id=${{ inputs.run_id }}"
            echo "run_id=${{ inputs.run_id }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          BRANCH="${{ inputs.branch }}"
          echo "Searching for a successful 'Build MicroAlign' run on branch: $BRANCH that has artifacts..."

          # Get the last 15 successful runs for the workflow on the branch
          mapfile -t RUNS < <(gh run list \
            --workflow "Build MicroAlign" \
            --branch "$BRANCH" \
            --status success \
            -L 15 \
            --json databaseId \
            -q '.[].databaseId')

          if [ ${#RUNS[@]} -eq 0 ]; then
            echo "No successful runs found for 'Build MicroAlign' on branch $BRANCH"
            exit 1
          fi

          # Pick the newest run that actually has artifacts
          CHOSEN=""
          for RID in "${RUNS[@]}"; do
            COUNT=$(gh run view "$RID" --json artifacts -q '.artifacts | length')
            echo "Run $RID has $COUNT artifact(s)"
            if [ "$COUNT" -gt 0 ]; then
              CHOSEN="$RID"
              break
            fi
          done

          if [ -z "$CHOSEN" ]; then
            echo "No runs with artifacts found among the last ${#RUNS[@]} successful runs."
            exit 1
          fi

          echo "Using run_id=$CHOSEN"
          echo "run_id=$CHOSEN" >> "$GITHUB_OUTPUT"

      - name: Download artifacts from chosen Build run
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.resolve.outputs.run_id }}
          path: dist
          merge-multiple: true

      - name: Verify artifacts exist
        run: |
          if [ ! -d dist ]; then
            echo "No artifacts were downloaded (dist/ missing)."
            exit 1
          fi
          echo "Downloaded files:"
          ls -lah dist || true
          # Fail if none of the expected bundles are present
          COUNT=$(ls -1 dist/* 2>/dev/null | wc -l | tr -d ' ')
          if [ "$COUNT" -eq 0 ]; then
            echo "No files found in dist/. Ensure your Build workflow uploads artifacts."
            exit 1
          fi

      - name: Create tag if missing
        run: |
          TAG="${{ inputs.tag }}"
          git fetch --tags
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping tag creation."
          else
            # Tag the current commit on the checked-out branch
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi

      - name: Create GitHub Release (attach downloaded bundles)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.title != '' && inputs.title || inputs.tag }}
          body: ${{ inputs.notes }}
          generate_release_notes: true
          files: |
            dist/*.zip
            dist/*.tar.gz
